apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","metadata":{"annotations":{"thoth-station.ninja/template-version":"1.0.2"},"labels":{"app":"kebechet"},"name":"kebechet-job","namespace":"thoth-test-core"},"spec":{"output":{"to":{"kind":"ImageStreamTag","name":"kebechet-job:latest"}},"resources":{"limits":{"cpu":"1","memory":"1Gi"},"requests":{"cpu":"1","memory":"1Gi"}},"runPolicy":"Serial","source":{"git":{"ref":"master","uri":"https://github.com/thoth-station/kebechet"},"type":"Git"},"strategy":{"dockerStrategy":{"dockerfilePath":"Dockerfile","noCache":true},"type":"Docker"},"triggers":[{"imageChange":{},"type":"ImageChange"},{"generic":{"secretReference":{"name":"generic-webhook-secret"}},"type":"Generic"}]}}
    thoth-station.ninja/template-version: 1.0.2
  creationTimestamp: '2019-10-30T15:54:05Z'
  labels:
    app: kebechet
  name: kebechet-job
  namespace: thoth-test-core
  resourceVersion: '420390689'
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/thoth-test-core/buildconfigs/kebechet-job
  uid: 80247be9-fb2d-11e9-975e-fa163e006653
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'kebechet-job:latest'
  postCommit: {}
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: '1'
      memory: 1Gi
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/thoth-station/kebechet'
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
      noCache: true
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - generic:
        secretReference:
          name: generic-webhook-secret
      type: Generic
status:
  lastVersion: 2

